<?php
//use Drupal\Core\Link;
use Drupal\Core\Url;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Datetime\DrupalDateTime;
use Drupal\node\Entity\Node;
use Drupal\vigilancia\Controller\VigilanciaController;
use Drupal\estrategia\Controller\EstrategiaController;
use Drupal\despliegue\Controller\DespliegueController;
use Drupal\decision\Controller\DecisionBlockController;
use Drupal\decision\Controller\DecisionController;

function decision_block_view_alter(array &$build, \Drupal\Core\Block\BlockPluginInterface $block) {
  $base_id=$block->getBaseId();
  $plugin_id=$block->getPluginId();
  
  if($plugin_id=='decision_left'){
    $build['#pre_render'][] = 'decision_block_decision_left_prerender';
  }
}

function decision_block_decision_left_prerender(array $build) {
    $decision_block_controller=new DecisionBlockController();
    $html=$decision_block_controller->decision_get_block_decision_left_content();
    $build['content']['#markup']=$html;
    return $build;
}

function decision_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  //print $form_id.'<br>';exit();
  $form_id_array=array('node_decision_form','node_decision_edit_form');
  if(in_array($form_id,$form_id_array)){
    $vigilancia=new VigilanciaController();
    $decision_controller=new DecisionController();
    $estrategia_controller=new EstrategiaController();
    $entity=$form_state->getFormObject()->getEntity();
    $nid=$entity->id();

    $vid=0;
    $vid_array=$entity->get('vid')->getValue();
    
    if(isset($vid_array[0]['value'])){
      $vid=$vid_array[0]['value'];
    }

    $form['field_my_group']['widget'][0]['target_id']['#prefix']='<div class="div_display_node">';
    $form['field_my_group']['widget'][0]['target_id']['#suffix']='</div>';

    $form['author']['#prefix']='<div class="div_display_node">';
    $form['author']['#suffix']='</div>';
    if($form_id=='node_decision_form'){
      $field_my_group_default_value=$vigilancia->vigilancia_get_grupo_default_value();
      if(!empty($field_my_group_default_value)){
        $form['field_my_group']['widget'][0]['target_id']['#default_value']=$field_my_group_default_value;
      }
    }

    $decision_row=$decision_controller->decision_get_decision_row($nid,$vid);
    $valor_decision=0;
    $fecha_cumplimiento=0; 
    $no_control_date=0;
    $node_estrategia_nid='';
    $node_despliegue_nid='';

    if(isset($decision_row->valor_decision) && !empty($decision_row->valor_decision)){
      $valor_decision=$decision_row->valor_decision;
    }
    if(isset($decision_row->fecha_cumplimiento) && !empty($decision_row->fecha_cumplimiento)){
      $fecha_cumplimiento=$decision_row->fecha_cumplimiento;
    }
    if(isset($decision_row->no_control_date) && !empty($decision_row->no_control_date)){
      $no_control_date=$decision_row->no_control_date;
    }  

    if(isset($decision_row->despliegue_nid) && !empty($decision_row->despliegue_nid)){
      $node_despliegue_nid=$decision_row->despliegue_nid;
    }

    $form['valor_decision']=array(
    '#type' => 'select',
    '#title' => t('Importance'),
    '#default_value' => $valor_decision,
    '#options'=>$estrategia_controller->estrategia_my_get_evaluacion_options('','valor_decision'),
    '#required' => FALSE
    );

    $node='';
    if(!empty($nid)){
      $node=Node::load($nid);
    }
    $fecha_cumplimiento=$decision_controller->decision_define_fecha_cumplimiento($node);

    $date_format = 'Y-m-d';
    $form['fecha_cumplimiento'] = array(
      '#type' => 'date',
      '#title' => t('Control Date'),
      '#value' =>$fecha_cumplimiento,
      '#date_format' => $date_format,
    );
  
    $form['no_control_date'] = array(
      '#type' => 'checkbox',
      '#title' => t('No Control Date'),
      '#default_value' => '0',  
      '#value' =>$no_control_date,
    );

    $form['#attached']['library'][] = 'estrategia/estrategia_inc_add_no_control_date_js';

    if($no_control_date=1){
      $form['control_date_fs']['fecha_cumplimiento']['#attributes']['disabled']='disabled';
    }

    $despliegue_nid = \Drupal::request()->query->get('nid');

    $form['despliegue_nid']=array(
    '#type' => 'hidden',
    '#value' => $despliegue_nid,
    );  

    $form['decision_guraso_fieldset'] = $decision_controller->create_decision_guraso_fieldset($nid,$despliegue_nid,$node_despliegue_nid,$checkbox_keys);

    $form['#attached']['library'][] = 'estrategia/estrategia_inc_add_js_txek_sel_estrategia_js';
    $form['#attached']['drupalSettings']['estrategia']['estrategia_txek']['idea_keys'] = $checkbox_keys;

  }
}

function decision_entity_presave(Drupal\Core\Entity\EntityInterface $entity) {
  //$decision_controller=new DecisionController();
  //$decision_controller->decision_on_entity_presave($entity);
  //$vigilancia->vigilancia_on_fuentes_entity_presave($entity);
  //$vigilancia->vigilancia_on_item_categorias_entity_presave($entity);
  //$vigilancia->vigilancia_on_item_tipodefuente_entity_presave($entity);
}
function decision_node_insert(Drupal\Core\Entity\EntityInterface $entity) {
  $decision_controller=new DecisionController();
  $decision_controller->decision_on_entity_save($entity,'insert');
}      
function decision_node_update(Drupal\Core\Entity\EntityInterface $entity) {
  $decision_controller=new DecisionController();
  $decision_controller->decision_on_entity_save($entity,'update');
}
function decision_menu_local_tasks_alter(&$data, $route_name) {
  $decision_block_controller=new DecisionBlockController();
  //if($estrategia_block_controller->estrategia_is_tab_estrategia()){
  if($decision_block_controller->decision_is_node('decision')){
    $vigilancia=new VigilanciaController();  
    $my_grupo=$vigilancia->vigilancia_get_grupo_default_value();
    $gid=0;
    
    if(!empty($my_grupo)){
      $gid=$my_grupo->id();
    }
    
    $nid=$decision_block_controller->decision_get_route_nid();

    $route_string='node.add';
    //$route_string='estrategia.node.add.decision';
    $data['tabs'][0]['decision_add_informacion'] = array(
      '#theme' => 'menu_local_task',
      '#link' => array(
        'title' => t('Add Information'),
        //'url' => Url::fromRoute('decision_add_informacion',array('group'=>$gid,'nid'=>$nid)),
        'url' => Url::fromRoute($route_string,array('node_type' =>'informacion','nid'=>$nid)),
        //'url' => Url::fromRoute($route_string,array('nid'=>$nid)),
        'localized_options' => array(
          'attributes' => array(
            'title' => t('Add Information'),
          ),
        ),
      ),
    );
  } 
}