<?php
//use Drupal\Core\Link;
use Drupal\wiki\Controller\WikiController;
use Drupal\Core\Access\AccessResult;
use Drupal\vigilancia\Controller\VigilanciaController;
use Drupal\wiki\Controller\WikiBlockController;
use Drupal\Core\Url;

function wiki_block_view_alter(array &$build, \Drupal\Core\Block\BlockPluginInterface $block) {
  $base_id=$block->getBaseId();
  $plugin_id=$block->getPluginId();
  if($plugin_id=='wiki_left'){
    //echo print_r($block,1);
    //exit();
    $build['#pre_render'][] = 'wiki_block_wiki_left_prerender';
  }else if($plugin_id=='wiki_left_simple_search'){
    $build['#pre_render'][] = 'wiki_block_wiki_left_simple_search_prerender';
  }
  //intelsat-2017
  //print $base_id.'<br>';
  //print $plugin_id.'<br>';  
}
function wiki_block_wiki_left_prerender(array $build) {
    $wiki_block_controller=new WikiBlockController();
    $html=$wiki_block_controller->wiki_get_block_wiki_left_content();
    $build['content']['#markup']=$html;
    return $build;
}
function wiki_block_wiki_left_simple_search_prerender(array $build){

    $form = \Drupal::formBuilder()->getForm('Drupal\wiki\Form\WikiSimpleSearchForm');
    $build['content']['#markup']=render($form);
    return $build;
}
/*function debate_block_access(\Drupal\block\Entity\Block $block, $operation, \Drupal\Core\Session\AccountInterface $account){
  if($operation=='view'){
    $result=1;
    $plugin_id=$block->getPluginId();
    $is_access=0;
    $debate_block_controller=new DebateBlockController();
    $visible_block=$debate_block_controller->debate_get_visible_block($plugin_id);
    $is_access=$visible_block['is_access'];
    $result=$visible_block['result'];

    if($is_access){
      return AccessResult::forbiddenIf(!$result);      
    }
    //print $plugin_id.'<br>';
  }
  return AccessResult::neutral();    
}*/
function wiki_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  //print $form_id.'<br>';exit();
  $form_id_array=array('node_wiki_form','node_wiki_edit_form');
  if(in_array($form_id,$form_id_array)){
    $vigilancia=new VigilanciaController();
    //$wiki_controller=new WikiController();
    
    $entity=$form_state->getFormObject()->getEntity();
    /*$nid=$entity->id();
    //print 'nid='.$nid;exit();
    $vid=0;
    $vid_array=$entity->get('vid')->getValue();
    if(isset($vid_array[0]['value'])){
      $vid=$vid_array[0]['value'];
    }*/
    
    //print 'vid='.$vid;exit();

    $form['field_my_group']['widget'][0]['target_id']['#prefix']='<div class="div_display_node">';
    $form['field_my_group']['widget'][0]['target_id']['#suffix']='</div>';
    //$vigilancia->print_form_fields($form);
    $form['author']['#prefix']='<div class="div_display_node">';
    $form['author']['#suffix']='</div>';
     $wiki_controller=new WikiController();
    if($form_id=='node_wiki_form'){
      $field_my_group_default_value=$vigilancia->vigilancia_get_grupo_default_value();
      if(!empty($field_my_group_default_value)){
        $form['field_my_group']['widget'][0]['target_id']['#default_value']=$field_my_group_default_value;
      }
      $my_request = \Drupal::request();
      $origin_nid=$my_request->get('origin_nid');
     // echo $origin_nid; exit();
     
      $origin_nid=$wiki_controller->wiki_solr_funciones_get_node_id_array_by_arg_string($origin_nid);
      //echo $origin_nid; exit();
      $form['origin_nid']=array(
           '#type'=>'hidden',
           '#default_value'=>$origin_nid,
      );
    }elseif ($form_id=='node_wiki_edit_form') {
      # code...
      /*$links_debate_html= $debate_controller->debate_links_debate_html();
      $links_debate_html=render($links_debate_html);*/
      $links_wiki_html= $wiki_controller->wiki_title_links_wiki_html();
     $form['links_wiki']=array(
           //'#type'=>'markup',
           //'#default_value'=>'prueba enlaces',
      // '#markup' => '<h3>Links</h3>'.$links_debate_html,
      '#markup' => $links_wiki_html,
      );

    }
 
    $fields_array=array('field_item_canal_category_tid');
    wiki_unset_form_fields_array($form,$fields_array);   
    wiki_grupo_add_categorias_form_field($form,$form_state, $form_id);
  }
}
function wiki_entity_presave(Drupal\Core\Entity\EntityInterface $entity) {
  $wiki_controller=new WikiController();
  $wiki_controller->wiki_on_entity_presave($entity);
}
function wiki_node_insert(Drupal\Core\Entity\EntityInterface $entity) {
  $wiki_controller=new WikiController();
  $wiki_controller->wiki_on_entity_save($entity,'insert');
}      
function wiki_node_update(Drupal\Core\Entity\EntityInterface $entity) {
  $wiki_controller=new WikiController();
  $wiki_controller->wiki_on_entity_save($entity,'update');
}
function wiki_grupo_add_categorias_form_field(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id){
  $wiki_controller=new WikiController();
  $wiki_controller->wiki_grupo_add_categorias_form_field($form,$form_state,$form_id);
}
function wiki_unset_form_fields_array(&$form,$fields_array){
  if(!empty($fields_array)){
    foreach($fields_array as $i=>$field){
      if(isset($form[$field])){
        unset($form[$field]);
      }
    }
  }
}
function wiki_menu_local_tasks_alter(&$data, $route_name) {
  $wiki_block_controller=new WikiBlockController();
  //if($estrategia_block_controller->estrategia_is_tab_estrategia()){
  if($wiki_block_controller->wiki_is_node('item')){
    $vigilancia=new VigilanciaController();  
    $my_grupo=$vigilancia->vigilancia_get_grupo_default_value();
    $gid=0;
    if(!empty($my_grupo)){
      $gid=$my_grupo->id();
    }
    //echo print_r($data,1);exit();
    
    $nid=$wiki_block_controller->wiki_get_route_item_nid();

  //  print $nid; exit();

    $route_string='enlazar_wiki';
    //$route_string='estrategia.node.add.despliegue';
    $data['tabs'][0]['enlazar_wiki'] = array(
      '#theme' => 'menu_local_task',
      '#link' => array(
        'title' => t('Link to Wiki'),
        //'url' => Url::fromRoute('estrategia_add_despliegue',array('group'=>$gid,'nid'=>$nid)),
        'url' => Url::fromRoute($route_string,array('group'=>$gid,'node'=>$nid)),
        //'url' => Url::fromRoute($route_string,array('nid'=>$nid)),
        'localized_options' => array(
          'attributes' => array(
            'title' => t('Link to Wiki'),
          ),
        ),
      ),
    );
  } 
}