<?php
use Drupal\Core\Access\AccessResult;
use Drupal\vigilancia\Controller\VigilanciaController;
use Drupal\Core\Url;
use Drupal\despliegue\Controller\DespliegueController;
use Drupal\despliegue\Controller\DespliegueBlockController;
use Drupal\estrategia\Controller\EstrategiaController;
//use Drupal\Core\Link;
//use Drupal\estrategia\Controller\EstrategiaBlockController;

function despliegue_block_view_alter(array &$build, \Drupal\Core\Block\BlockPluginInterface $block) {
  $base_id=$block->getBaseId();
  $plugin_id=$block->getPluginId();
  if($plugin_id=='despliegue_left'){
    //echo print_r($block,1);
    //exit();
    $build['#pre_render'][] = 'despliegue_block_despliegue_left_prerender';
  }
}

function despliegue_block_despliegue_left_prerender(array $build) {
    $despliegue_block_controller=new DespliegueBlockController();
    $html=$despliegue_block_controller->despliegue_get_block_despliegue_left_content();
    $build['content']['#markup']=$html;
    return $build;
}

function despliegue_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  //print $form_id.'<br>';exit();
  $form_id_array=array('node_despliegue_form','node_despliegue_edit_form');
  if(in_array($form_id,$form_id_array)){
    $vigilancia=new VigilanciaController();
    $despliegue_controller=new DespliegueController();
    $estrategia_controller=new EstrategiaController();
    $entity=$form_state->getFormObject()->getEntity();
    $nid=$entity->id();
    //print 'nid='.$nid;exit();
    $vid=0;
    $vid_array=$entity->get('vid')->getValue();
    if(isset($vid_array[0]['value'])){
      $vid=$vid_array[0]['value'];
    }
    
    //print 'vid='.$vid;exit();

    $form['field_my_group']['widget'][0]['target_id']['#prefix']='<div class="div_display_node">';
    $form['field_my_group']['widget'][0]['target_id']['#suffix']='</div>';
    //$vigilancia->print_form_fields($form);
    $form['author']['#prefix']='<div class="div_display_node">';
    $form['author']['#suffix']='</div>';
    if($form_id=='node_despliegue_form'){
      $field_my_group_default_value=$vigilancia->vigilancia_get_grupo_default_value();
      if(!empty($field_my_group_default_value)){
        $form['field_my_group']['widget'][0]['target_id']['#default_value']=$field_my_group_default_value;
      }
    }

    $despliegue_row=$despliegue_controller->despliegue_get_despliegue_row($nid,$vid);
    //echo print_r($estrategia_row,1);exit();
    $importancia_despliegue=0;
    if(isset($despliegue_row->importancia_despliegue) && !empty($despliegue_row->importancia_despliegue)){
      $importancia_despliegue=$despliegue_row->importancia_despliegue;
    }

    $form['importancia_despliegue']=array(
    '#type' => 'select',
    '#title' => t('Importance'),
    '#default_value' => $importancia_despliegue,
    '#options'=>$estrategia_controller->estrategia_my_get_evaluacion_options('','importancia_despliegue'),
    '#required' => FALSE
    );
  
    //$post=\Drupal::request()->request->all();
    //echo print_r($post,1); exit();

    $estrategia_nid = \Drupal::request()->query->get('nid');
    //echo print_r($query,1); exit();

    $form['estrategia_nid']=array(
    '#type' => 'hidden',
    '#value' => $estrategia_nid,
    );
  }
}

function despliegue_entity_presave(Drupal\Core\Entity\EntityInterface $entity) {
  //$despliegue_controller=new DespliegueController();
  //$despliegue_controller->despliegue_on_entity_presave($entity);
  //$vigilancia->vigilancia_on_fuentes_entity_presave($entity);
  //$vigilancia->vigilancia_on_item_categorias_entity_presave($entity);
  //$vigilancia->vigilancia_on_item_tipodefuente_entity_presave($entity);
}
function despliegue_node_insert(Drupal\Core\Entity\EntityInterface $entity) {
  $despliegue_controller=new DespliegueController();
  $despliegue_controller->despliegue_on_entity_save($entity,'insert');
}      
function despliegue_node_update(Drupal\Core\Entity\EntityInterface $entity) {
  $despliegue_controller=new DespliegueController();
  $despliegue_controller->despliegue_on_entity_save($entity,'update');
}
function despliegue_menu_local_tasks_alter(&$data, $route_name) {
  $despliegue_block_controller=new DespliegueBlockController();
  //if($estrategia_block_controller->estrategia_is_tab_estrategia()){
  if($despliegue_block_controller->despliegue_is_node('despliegue')){
    $vigilancia=new VigilanciaController();  
    $my_grupo=$vigilancia->vigilancia_get_grupo_default_value();
    $gid=0;
    if(!empty($my_grupo)){
      $gid=$my_grupo->id();
    }
    //echo print_r($data,1);exit();
    
    $nid=$despliegue_block_controller->despliegue_get_route_nid();

    $route_string='node.add';
    //$route_string='estrategia.node.add.despliegue';
    $data['tabs'][0]['despliegue_add_decision'] = array(
      '#theme' => 'menu_local_task',
      '#link' => array(
        'title' => t('Add Decision'),
        //'url' => Url::fromRoute('despliegue_add_decision',array('group'=>$gid,'nid'=>$nid)),
        'url' => Url::fromRoute($route_string,array('node_type' =>'decision','nid'=>$nid)),
        //'url' => Url::fromRoute($route_string,array('nid'=>$nid)),
        'localized_options' => array(
          'attributes' => array(
            'title' => t('Add Decision'),
          ),
        ),
      ),
    );
  } 
}